# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2597c33ea645b1d389c1b3148310e850123b5e3bb4d621e82f86df32688b62ea1bec58349a8323439ce954a3d9beba3ff8bba9bfbf06baf78ea60c54ff5dba06

test:
  secret_key_base: c56771eef4f432fc5c7f974df33ff2106fc0078599bc3a09fb79285666c3710c032a219be2df3bf538f5830b0cbd21a8e03f6d7c516328cd2919409c6cd84dc1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
